### ISSUE TITLE
建议将视频的封面和背景图也写入vsmeta文件中。

### ISSUE THREAD

**Issue by laiwenle** [JuanWoo/nfo-to-vsmeta#1]
成功将部分视频的nfo的信息转换成vsmeta，但有一些还是不成功。另外建议将视频所在文件夹中的post.jpg和fanart.jpg也写入到vsmeta文件的海报和背景中。不然转换后的vsmeta索引后都不是海报墙了。谢谢大佬。

**Comment by JuanWoo** [comment]
海报可以在群晖video中，“设置 > 高级 > 视频封面设置”设定默认加载的海报文件名，将你刮削的海报名填到第一位，例如你的是post.jpg;
背景图暂时无法设定，在video编辑背景图信息后，vsmeta文件内容是加密的。
----20230711更新
研究了下背景图是base64位方式存储，但中间还有写特定分隔符。待进一步研究写法后，应该可以支持。

**Comment by Huaweidev** [comment]
> 海报可以在群晖video中，“设置 > 高级 > 视频封面设置”设定默认加载的海报文件名，将你刮削的海报名填到第一位，例如你的是post.jpg; 背景图暂时无法设定，在video编辑背景图信息后，vsmeta文件内容是加密的。

好用，将海报图片名称改成“poster.jpg”可以正常显示封面。为什么nfo里面有很多字段但是转换成vsmeta后，在Video Station里面还是看不到很多字段（如下图所示）？如果不兼容那这样转换的意义是什么？
![07-08_21-36-24](https://github.com/JuanWoo/nfo-to-vsmeta/assets/10258421/ad1b1fcd-b5ab-46bd-972d-c0b064c36ae3)

**Comment by JuanWoo** [comment]
> 

提供一下不能正常显示的 nfo和vsmeta两份文件

**Comment by laiwenle** [comment]
> 海报可以在群晖video中，“设置 > 高级 > 视频封面设置”设定默认加载的海报文件名，将你刮削的海报名填到第一位，例如你的是post.jpg; 背景图暂时无法设定，在video编辑背景图信息后，vsmeta文件内容是加密的。 ----20230711更新 研究了下背景图是base64位方式存储，但中间还有写特定分隔符。待进一步研究写法后，应该可以支持。

https://github.com/ylqjgm/AVMeta，这个项目是用go语言编写的，功能多一点。有一个功能是将nfo和同文件夹里的poster和fanart转换写入vsmeta文件中，大部分是可以转换成功的，能将nfo信息转化也比较多。不过用起来还是有问题：1.如果nfo文件中的发行日期之类的日期是0000-00-00的话，转成vsmeta就读不出来；2.如果同文件夹的poster和fanart的文件大小大于400kb的话，转化成vsmeta对应的封面和背景只能显示一部分，下面都是黑色，要手动编辑封面和背景才行。谢谢大佬百忙中回复我。

**Comment by Huaweidev** [comment]
@laiwenle，
你好，我们两需求和探索过程高度重合，能否加个联系方式交流一下？

**Comment by 1525745393** [comment]
大佬有解决方法了没

**Comment by JuanWoo** [comment]
@laiwenle @Huaweidev @1525745393 已更新支持海报图和背景图识别，并修复了一些取错nfo的bug，请见使用说明。
此问题关闭，测试有问题再新开。
![image](https://github.com/JuanWoo/nfo-to-vsmeta/assets/4869539/5c089d2c-8064-4c94-bf42-c6e3117e2492)

**Comment by 1525745393** [comment]
感谢大佬 明天试一下
