### ISSUE TITLE
您好，我把vsmeta和视频文件同名同目录，为什么视频信息更新不了？方便加个微信问你一下vsmeta更新的问题吗？我的号码是137464169，多谢

### ISSUE THREAD

**Issue by zhuantai** [JuanWoo/nfo-to-vsmeta#10]
您好，我把vsmeta和视频文件同名同目录，为什么视频信息更新不了？方便加个微信问你一下vsmeta更新的问题吗？我的号码是137464169，多谢

**Comment by JuanWoo** [comment]
直接在这里反馈问题就可以了。如果是相同的问题，其他人也能共享得知。

**Comment by zhuantai** [comment]
已收到您的来件！祝您生活愉快！

**Comment by 1525745393** [comment]
> 您好，我把vsmeta和视频文件同名同目录，为什么视频信息更新不了？方便加个微信问你一下vsmeta更新的问题吗？我的号码是137464169，多谢

信息太少，文件夹路径 视频文件夹详情发出来看看，群晖媒体库布置的是（电影） 还是（电视节目）

**Comment by zhuantai** [comment]
已收到您的来件！祝您生活愉快！

**Comment by zhuantai** [comment]
多谢，我后来自己写了一套根据我的文件名生成vsmeta文件格式的代码，搞好了




Tiger。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JuanWoo/nfo-to-vsmeta"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月28日(星期三) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JuanWoo/nfo-to-vsmeta] 您好，我把vsmeta和视频文件同名同目录，为什么视频信息更新不了？方便加个微信问你一下vsmeta更新的问题吗？我的号码是137464169，多谢 (Issue #10)





 
Closed #10 as completed.
