### ISSUE TITLE
大佬视频后缀名.ts无法转换

### ISSUE THREAD

**Issue by 1525745393** [JuanWoo/nfo-to-vsmeta#3]
![Screenshot_2024-03-18-01-11-03-855_com.synology.DSfile.jpg](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/9c8f7edc-5633-45b5-b963-2d20e76add62)

![IMG_20240318_011649.jpg](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/6fa84bca-5c18-4ebf-ab3e-175188e91010)

**Comment by 1525745393** [comment]
![screenshot-1710695885057.png](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/446a3d55-ca67-4b58-be5a-cc8b493f4795)

**Comment by JuanWoo** [comment]
JDKR04.nfo 这份文件内容贴上来我看下，有可能是nfo文件的格式不兼容

**Comment by 1525745393** [comment]
> JDKR04.nfo 这份文件内容贴上来我看下，有可能是nfo文件的格式不兼容

﻿<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<movie>
  <plot />
  <outline />
  <customrating>NC-17</customrating>
  <lockdata>false</lockdata>
  <dateadded>2022-12-10 23:01:51</dateadded>
  <title>JDKR04 忘记交电费的邻居</title>
  <originaltitle>JDKR04 忘记交电费的邻居</originaltitle>
  <actor>
    <name>由奈</name>
    <type>Actor</type>
  </actor>
  <sorttitle>JDKR04 忘记交电费的邻居</sorttitle>
  <mpaa>NC-17</mpaa>
  <countrycode>CN</countrycode>
  <runtime>48</runtime>
  <genre>1080P</genre>
  <genre>JDKR</genre>
  <genre>由奈</genre>
  <genre>国产</genre>
  <genre>系列: 精东影业抗日奇侠系列</genre>
  <genre>片商: 精东影业</genre>
  <genre>发行: 精东影业</genre>
  <studio>精东影业</studio>
  <tag>1080P</tag>
  <tag>JDKR</tag>
  <tag>由奈</tag>
  <tag>国产</tag>
  <tag>系列: 精东影业抗日奇侠系列</tag>
  <tag>片商: 精东影业</tag>
  <tag>发行: 精东影业</tag>
  <set>
    <name>精东影业抗日奇侠系列</name>
  </set>
  <fileinfo>
    <streamdetails>
      <video>
        <codec>h264</codec>
        <micodec>h264</micodec>
        <bitrate>4556874</bitrate>
        <width>1920</width>
        <height>1080</height>
        <aspect>16:9</aspect>
        <aspectratio>16:9</aspectratio>
        <framerate>30</framerate>
        <scantype>progressive</scantype>
        <default>False</default>
        <forced>False</forced>
        <duration>48</duration>
        <durationinseconds>2904</durationinseconds>
      </video>
      <audio>
        <codec>aac</codec>
        <micodec>aac</micodec>
        <bitrate>191900</bitrate>
        <scantype>progressive</scantype>
        <channels>2</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
    </streamdetails>
  </fileinfo>
  <num>JDKR04</num>
  <series>精东影业抗日奇侠系列</series>
  <maker>精东影业</maker>
  <publisher>精东影业</publisher>
  <label>精东影业</label>
  <cover>https://img.cnav5.com/2022/11/18/JDKR04.jpg</cover>
  <website>https://cnmdb.net/JDKR04</website>
</movie>

**Comment by 1525745393** [comment]
> JDKR04.nfo 这份文件内容贴上来我看下，有可能是nfo文件的格式不兼容
[JDKR04.TXT](https://github.com/JuanWoo/nfo-to-vsmeta/files/14630813/JDKR04.TXT)

**Comment by JuanWoo** [comment]
已更新版本修复。

**Comment by 1525745393** [comment]
> 已更新版本修复。

感谢大佬 等我把封面裁剪好 在试一下
