### ISSUE TITLE
试了一下：视频的封面和背景图还是写入不到vsmeta文件中

### ISSUE THREAD

**Issue by 1525745393** [JuanWoo/nfo-to-vsmeta#4]
![Screenshot_2024-03-18-02-58-31-675_com.synology.DSfile.jpg](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/0c7264ab-ef51-491e-ada3-944e25f60c01)

![IMG_20240318_030229.jpg](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/6adf08e0-9193-44b5-8bed-18d90f6bd4b0)

![screenshot-1710701961868.png](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/d882c246-f827-4556-9305-649a2d34d673)

**Comment by JuanWoo** [comment]
你的封面、背景文件实际是带了番号的，有两个办法解决，任选其一。
1、修改21 22这两行代码，识别文件名称加上【os.path.splitext(filename)[0] + 】
```
                poster_path = os.path.join(root, poster)#修改前
                fanart_path = os.path.join(root, fanart)#修改前
```
改成
```
                poster_path = os.path.join(root, os.path.splitext(filename)[0] + poster)#修改后
                fanart_path = os.path.join(root, os.path.splitext(filename)[0] + fanart)#修改后
```
2、修改刮削工具背景图和封面的命名规则，改成不带番号及CD编号，只用 fanart.jpg、poster.jpg 命名
![image](https://github.com/JuanWoo/nfo-to-vsmeta/assets/4869539/9606a922-b441-492d-bfc1-41e5d06f3a9a)

**Comment by 1525745393** [comment]
感谢大佬 可以写进去了
