### ISSUE TITLE
自动人脸识别封面裁剪

### ISSUE THREAD

**Issue by 1525745393** [JuanWoo/nfo-to-vsmeta#5]
大佬 有推荐的软件没，手动剪了一百多个头大啊

**Comment by JuanWoo** [comment]
没太理解是要截图干什么，是刮削到封面图片，所以从已有背景图里截一部分当封面？

**Comment by 1525745393** [comment]
一般 无码 和国产刮削封面图都是背景图复制的，因为它的人物不是统一边的所以无法批量处理，所以要人脸识别定位在裁剪封面

**Comment by 1525745393** [comment]
主要是群晖封面一般都是居中显示，如果不裁剪直接用的话显示是很乱

**Comment by 1525745393** [comment]
![Screenshot_2024-03-22-09-40-55-642_com.synology.dsvideo.jpg](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/62fe7e9d-7021-4a7f-8f2c-13dfea4207f7)

**Comment by JuanWoo** [comment]
你可以尝试用人脸识别相册，这类应用现在应该比较多。找一个可以然后通过手机端浏览，用手机端截屏后整理到对应目录去。
比如这个项目 https://gitee.com/mulanbay-face

**Comment by 1525745393** [comment]
https://github.com/opencv/opencv
https://github.com/exinnet/tclip这两个项目还行，不知道怎么弄 像你的这个这样直接搜索文件夹指定项目，在通过人脸识别人像定位裁剪，裁剪过后图像保存到原文件自动重命名或移动到指定文件
