### ISSUE TITLE
大佬新版封面带番号的 修改了 你提供的代码无法识别

### ISSUE THREAD

**Issue by 1525745393** [JuanWoo/nfo-to-vsmeta#8]

**Comment by 1525745393** [comment]
提示

**Comment by 1525745393** [comment]
当前状态：0 (正常)
标准输出/错误：
未定义名称'posterPath'

**Comment by 1525745393** [comment]
<!-- 上传 Screenshot_2024-03-25-04-47-01-480_com.tencent.androidqqmail.jpg

**Comment by 1525745393** [comment]
[SIVR-017-CD1.TXT](https://github.com/JuanWoo/nfo-to-vsmeta/files/14736851/SIVR-017-CD1.TXT)
!/106818742/144f0a6e-c45f-48e9-91e5-6eb3b9e804d6)
![1711315519091](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/0ca00d68-4dd8-4993-877d-a80a360174dc)

**Comment by 1525745393** [comment]
![批注 2024-03-25 053326](https://github.com/JuanWoo/nfo-to-vsmeta/assets/106818742/51eb3e72-588d-4af7-9215-dc6f1b3d79fe)
[DSVR-595-CD1.TXT](https://github.com/JuanWoo/nfo-to-vsmeta/files/14736875/DSVR-595-CD1.TXT)

**Comment by JuanWoo** [comment]
你分支上25 26两行代码要改下
```
                poster_path = os.path.join(root, os.path.splitext(filename)[0] + poster)#背景文件带了番号的
                fanart_path = os.path.join(root, os.path.splitext(filename)[0] + fanart)#封面、背景文件带了番号的
```
改成
```
                posterPath = os.path.join(root, os.path.splitext(filename)[0] + poster)#背景文件带了番号的
                fanartPath = os.path.join(root, os.path.splitext(filename)[0] + fanart)#封面、背景文件带了番号的
```

**Comment by 1525745393** [comment]
> 你分支上25 26两行代码要改下
> 
> ```
>                 poster_path = os.path.join(root, os.path.splitext(filename)[0] + poster)#背景文件带了番号的
>                 fanart_path = os.path.join(root, os.path.splitext(filename)[0] + fanart)#封面、背景文件带了番号的
> ```
> 
> 改成
> 
> ```
>                 posterPath = os.path.join(root, os.path.splitext(filename)[0] + poster)#背景文件带了番号的
>                 fanartPath = os.path.join(root, os.path.splitext(filename)[0] + fanart)#封面、背景文件带了番号的
> ```

好的 我试下
