### ISSUE TITLE
能否加个参数可以反向 vsmeta 转 nfo

### ISSUE THREAD

**Issue by chenfeicqq** [JuanWoo/nfo-to-vsmeta#9]
之前都是用 video station 来搜刮的，想转成 nfo，在 kodi 上展示海报等信息。感谢大佬

**Comment by JuanWoo** [comment]
vsmeta的信息量比nfo信息少，反向转缺少很多内容，没有必要。
不如你直接用刮削工具，从imdb刮nfo，是不会影响你已有vsmeta的

**Comment by JuanWoo** [comment]
vsmeta的信息量比nfo信息少，反向转缺少很多内容，没有必要。
不如你直接用刮削工具，从imdb刮nfo，是不会影响你已有vsmeta的
